# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages
env:
  PUBLISH_DIR: MatchStatCharts/bin/Debug/net9.0/wwwroot
on:
  # Runs on pushes targeting the default branch
  push:
    paths:  
      - MatchStatCharts/**
    branches: 
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Get Latest .Net SDK
        uses: actions/setup-dotnet@d4c94342e560b34958eacfc5d055d21461ed1c5d # v5.0.0
        with:
          dotnet-version: '10.0.x'
      
      - name: Publish app
        run:  dotnet publish MatchStatsCharts -c Release

      - name: Rewrite base href
        uses: TheBoru/ghaction-rewrite-base-href@f797f3d0f16f5c44672f5408ecbb9eb6d617b17c # v1.1.0
        with:
          html_path: ${{ env.PUBLISH_DIR }}/index.html
          base_href: /MatchStatCharts/
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
